### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by MikiSoft** [kholia/exetractor-clone#1]
Since this is written in Python 2 it can't extract `PYTHONSCRIPT` if it's written in Python 3 - it throws an exception `ValueError: bad marshal data (unknown type code)`.

**Comment by kholia** [comment]
Please attach a sample file which exhibits this problem. Also describe the steps used to create the sample file.

**Comment by MikiSoft** [comment]
It's rather simple - just use the latest version of py2exe and make an EXE file of some Python 3 script.

**Comment by kholia** [comment]
I am not planning on fixing this. This project is not updated anymore.

**Comment by kholia** [comment]
https://github.com/matiasb/unpy2exe might work.
