### ISSUE TITLE
Not working for PyInstaller

### ISSUE THREAD

**Issue by ayush12garg** [kholia/exetractor-clone#2]
python ArchiveExtractor.py dist/run_ui
Error parsing archive, is this a valid PyInstaller generated app?

Not working for Pyinstaller. As new Pyinstaller is creating .so with the executable file.

**Comment by kholia** [comment]
This project is not maintained / updated. Find something else or build your own tool.

**Comment by kholia** [comment]
https://sourceforge.net/projects/pyinstallerextractor/ might work instead.
